services:
  - type: web
    name: curaflow-backend-api
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: PORT
        value: 8080
      - key: DB_DDL_AUTO
        value: update
      - key: JWT_EXPIRATION_MS
        value: 86400000
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: JWT_SECRET
        sync: false
