services:
  - type: web
    name: curaflow-backend-api
    runtime: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: DB_DDL_AUTO
        value: update
      - key: JWT_EXPIRATION_MS
        value: 86400000
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: JWT_SECRET
        generateValue: true
