SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE medical_records;
TRUNCATE TABLE appointments;
TRUNCATE TABLE bills;
TRUNCATE TABLE doctors;
TRUNCATE TABLE patients;
TRUNCATE TABLE departments;
TRUNCATE TABLE users;
TRUNCATE TABLE hospitals;

SET FOREIGN_KEY_CHECKS=1;
